---
- name: check if jetson                                           
  stat:                                                                     
    path: /etc/nv_tegra_release                                             
  register: is_jetson                                                       
                                                                                 
- name: activate 6 cores if is jetson
  shell: /usr/sbin/nvpmodel -m 2 
  when:                                                                     
    - is_jetson.stat.exists == true 

