---
#- stat:
#    path: /etc/nv_tegra_release
#  register: is_jetson                                                       
                                                                                 
- include: jetson.yml
  # when: is_jetson.stat.exists 

- name: install devtools packages
  apt:
    pkg:
      - wget
      - curl
      - apt-transport-https
 
- include: vscode-{{ ansible_distribution|lower }}-{{ ansible_architecture|lower }}.yml

