- hosts: localhost
  become: yes

  vars:
    username: "{{ username }}" 
    userhome: "{{ userhome }}"
    hostname: "{{ hostname }}"
    primary: "{{ primary }}"
    secondary: "{{ secondary }}"

  roles:
    - name: software  
    - name: user
    - name: dunst
    - name: i3
    - name: i3blocks
    - name: x
    - name: vim
    - name: devtools
