#
# ansible role to configure X:
#
---
- name: upload xinitrc
  become_user: "{{ username }}"
  template:
    src: "xinitrc.j2"
    dest: "{{ userhome }}/.xinitrc"
    mode: '0755'
  tags:
    - configuration

- name: X configuration - Copy "{{ userhome }}/.Xresources"
  become_user: "{{ username }}"
  template:
    src: "Xresources.j2"
    dest: "{{ userhome }}/.Xresources"
    mode: '0755'
  tags:
    - configuration

- name: update dotbashrc
  blockinfile:
    path: "{{ userhome }}/.bashrc"
    block: |
      if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]] ; then
        if [ "$HOSTNAME"=="{{ hostname }}" ] ; then
          startx
        fi
      fi
  tags:
    - configuration

