#
# ansible role to setup config i3:
#
---
- name: i3 Configuration - create i3 directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/i3"
    state: directory
  tags:
    - i3

- name: i3 configuration - copy binaries
  become_user: "{{ username }}"
  synchronize:
    src: bin/
    dest: "{{ userhome }}/.config/i3/bin/"
    recursive: true
  tags:
    - i3

- name: i3 configuration - copy bg
  become_user: "{{ username }}"
  copy:
    src: colors.png
    dest: "{{ userhome }}/.config/i3/"
  tags:
    - i3

- name: i3 configuration - copy config files
  become_user: "{{ username }}"
  template:
    src: {{ item }}.j2
    dest: "{{ userhome }}/.config/i3/{{ item }}"
    mode: '0644'
  with_items:
    - config
    - i3status.conf
    - i3blocks.conf
  tags:
    - i3
