#!/usr/bin/env bash
xmodmap ~/.Xmodmap #(note: this is for my custom key assignments)
xrdb -merge ~/.Xresources #(to load ~/.Xresources if you use it)
dbus-update-activation-environment DISPLAY XAUTHORITY
exec i3 --force-xinerama #-V >>~/.i3/i3log 2>&1 #(needs to be the last line)
